services:
  - type: web
    name: yellowspace
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mimi_ecom.wsgi
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: yellowspace.onrender.com
