services:
  - type: web
    name: mimi-ecom
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: mimi-ecom-db
          property: connectionString
    disk:
      name: mimi-ecom-disk
      mountPath: /mimi_ecom/media
      sizeGB: 1

  - type: redis
    name: mimi-ecom-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru

databases:
  - name: mimi-ecom-db
    plan: starter
    databaseName: mimi_ecom
    user: mimi_ecom_user