# Generated by Django 5.2.3 on 2025-07-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paiement_confirmation',
            field=models.ImageField(blank=True, help_text='Upload payment receipt image', null=True, upload_to='payment_receipts/'),
        ),
    ]
